/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const EventStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'live' : IDL.Null,
  'completed' : IDL.Null,
});
export const EventCategory = IDL.Variant({
  'seminar' : IDL.Null,
  'workshop' : IDL.Null,
  'hackathon' : IDL.Null,
  'podcast' : IDL.Null,
  'webinar' : IDL.Null,
  'techCarnival' : IDL.Null,
  'summit' : IDL.Null,
  'aiConference' : IDL.Null,
});
export const TechEvent = IDL.Record({
  'id' : IDL.Nat,
  'status' : EventStatus,
  'registrationLimit' : IDL.Nat,
  'isPublished' : IDL.Bool,
  'bannerBlobId' : IDL.Opt(IDL.Text),
  'currentRegistrations' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isFree' : IDL.Bool,
  'specialInstructions' : IDL.Opt(IDL.Text),
  'onlineLink' : IDL.Opt(IDL.Text),
  'endDateTime' : IDL.Opt(IDL.Int),
  'category' : EventCategory,
  'price' : IDL.Float64,
  'dateTime' : IDL.Int,
  'location' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const EventRegistration = IDL.Record({
  'id' : IDL.Nat,
  'eventId' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'isPaid' : IDL.Bool,
  'email' : IDL.Text,
  'stripePaymentId' : IDL.Opt(IDL.Text),
  'contactNumber' : IDL.Text,
  'organization' : IDL.Opt(IDL.Text),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createEvent' : IDL.Func([TechEvent], [IDL.Nat], []),
  'createTestimonial' : IDL.Func([Testimonial], [IDL.Nat], []),
  'deleteEvent' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvents' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(TechEvent)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'publishEvent' : IDL.Func([IDL.Nat], [], []),
  'publishTestimonial' : IDL.Func([IDL.Nat], [], []),
  'registerForEvent' : IDL.Func([EventRegistration], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'subscribeToNewsletter' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unsubscribe' : IDL.Func([IDL.Text], [], []),
  'updateEvent' : IDL.Func([IDL.Nat, TechEvent], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const EventStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'live' : IDL.Null,
    'completed' : IDL.Null,
  });
  const EventCategory = IDL.Variant({
    'seminar' : IDL.Null,
    'workshop' : IDL.Null,
    'hackathon' : IDL.Null,
    'podcast' : IDL.Null,
    'webinar' : IDL.Null,
    'techCarnival' : IDL.Null,
    'summit' : IDL.Null,
    'aiConference' : IDL.Null,
  });
  const TechEvent = IDL.Record({
    'id' : IDL.Nat,
    'status' : EventStatus,
    'registrationLimit' : IDL.Nat,
    'isPublished' : IDL.Bool,
    'bannerBlobId' : IDL.Opt(IDL.Text),
    'currentRegistrations' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isFree' : IDL.Bool,
    'specialInstructions' : IDL.Opt(IDL.Text),
    'onlineLink' : IDL.Opt(IDL.Text),
    'endDateTime' : IDL.Opt(IDL.Int),
    'category' : EventCategory,
    'price' : IDL.Float64,
    'dateTime' : IDL.Int,
    'location' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const EventRegistration = IDL.Record({
    'id' : IDL.Nat,
    'eventId' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'isPaid' : IDL.Bool,
    'email' : IDL.Text,
    'stripePaymentId' : IDL.Opt(IDL.Text),
    'contactNumber' : IDL.Text,
    'organization' : IDL.Opt(IDL.Text),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createEvent' : IDL.Func([TechEvent], [IDL.Nat], []),
    'createTestimonial' : IDL.Func([Testimonial], [IDL.Nat], []),
    'deleteEvent' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvents' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(TechEvent)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'publishEvent' : IDL.Func([IDL.Nat], [], []),
    'publishTestimonial' : IDL.Func([IDL.Nat], [], []),
    'registerForEvent' : IDL.Func([EventRegistration], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'subscribeToNewsletter' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unsubscribe' : IDL.Func([IDL.Text], [], []),
    'updateEvent' : IDL.Func([IDL.Nat, TechEvent], [], []),
  });
};

export const init = ({ IDL }) => { return []; };