/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type EventCategory = { 'seminar' : null } |
  { 'workshop' : null } |
  { 'hackathon' : null } |
  { 'podcast' : null } |
  { 'webinar' : null } |
  { 'techCarnival' : null } |
  { 'summit' : null } |
  { 'aiConference' : null };
export interface EventRegistration {
  'id' : bigint,
  'eventId' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'isPaid' : boolean,
  'email' : string,
  'stripePaymentId' : [] | [string],
  'contactNumber' : string,
  'organization' : [] | [string],
}
export type EventStatus = { 'upcoming' : null } |
  { 'live' : null } |
  { 'completed' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TechEvent {
  'id' : bigint,
  'status' : EventStatus,
  'registrationLimit' : bigint,
  'isPublished' : boolean,
  'bannerBlobId' : [] | [string],
  'currentRegistrations' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'isFree' : boolean,
  'specialInstructions' : [] | [string],
  'onlineLink' : [] | [string],
  'endDateTime' : [] | [bigint],
  'category' : EventCategory,
  'price' : number,
  'dateTime' : bigint,
  'location' : string,
}
export interface Testimonial {
  'id' : bigint,
  'content' : string,
  'isPublished' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'role' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createEvent' : ActorMethod<[TechEvent], bigint>,
  'createTestimonial' : ActorMethod<[Testimonial], bigint>,
  'deleteEvent' : ActorMethod<[bigint], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEvents' : ActorMethod<[[] | [string], [] | [string]], Array<TechEvent>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [string]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'publishEvent' : ActorMethod<[bigint], undefined>,
  'publishTestimonial' : ActorMethod<[bigint], undefined>,
  'registerForEvent' : ActorMethod<[EventRegistration], bigint>,
  'saveCallerUserProfile' : ActorMethod<[string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'subscribeToNewsletter' : ActorMethod<[string], bigint>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unsubscribe' : ActorMethod<[string], undefined>,
  'updateEvent' : ActorMethod<[bigint, TechEvent], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];