/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface TechEvent {
    id: bigint;
    status: EventStatus;
    registrationLimit: bigint;
    isPublished: boolean;
    bannerBlobId?: string;
    currentRegistrations: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    isFree: boolean;
    specialInstructions?: string;
    onlineLink?: string;
    endDateTime?: bigint;
    category: EventCategory;
    price: number;
    dateTime: bigint;
    location: string;
}
export interface EventRegistration {
    id: bigint;
    eventId: bigint;
    name: string;
    createdAt: bigint;
    isPaid: boolean;
    email: string;
    stripePaymentId?: string;
    contactNumber: string;
    organization?: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Testimonial {
    id: bigint;
    content: string;
    isPublished: boolean;
    name: string;
    createdAt: bigint;
    role: string;
}
export enum EventCategory {
    seminar = "seminar",
    workshop = "workshop",
    hackathon = "hackathon",
    podcast = "podcast",
    webinar = "webinar",
    techCarnival = "techCarnival",
    summit = "summit",
    aiConference = "aiConference"
}
export enum EventStatus {
    upcoming = "upcoming",
    live = "live",
    completed = "completed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createEvent(event: TechEvent): Promise<bigint>;
    createTestimonial(testimonial: Testimonial): Promise<bigint>;
    deleteEvent(eventId: bigint): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getEvents(category: string | null, status: string | null): Promise<Array<TechEvent>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<string | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    publishEvent(eventId: bigint): Promise<void>;
    publishTestimonial(testimonialId: bigint): Promise<void>;
    registerForEvent(registration: EventRegistration): Promise<bigint>;
    saveCallerUserProfile(profile: string): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    subscribeToNewsletter(email: string): Promise<bigint>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unsubscribe(email: string): Promise<void>;
    updateEvent(eventId: bigint, event: TechEvent): Promise<void>;
}
import type { EventCategory as _EventCategory, EventRegistration as _EventRegistration, EventStatus as _EventStatus, StripeSessionStatus as _StripeSessionStatus, TechEvent as _TechEvent, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createEvent(arg0: TechEvent): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(to_candid_TechEvent_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(to_candid_TechEvent_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createTestimonial(arg0: Testimonial): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTestimonial(arg0);
            return result;
        }
    }
    async deleteEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvents(arg0: string | null, arg1: string | null): Promise<Array<TechEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvents(to_candid_opt_n18(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvents(to_candid_opt_n18(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async publishEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishEvent(arg0);
            return result;
        }
    }
    async publishTestimonial(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishTestimonial(arg0);
            return result;
        }
    }
    async registerForEvent(arg0: EventRegistration): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerForEvent(to_candid_EventRegistration_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerForEvent(to_candid_EventRegistration_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async subscribeToNewsletter(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribeToNewsletter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribeToNewsletter(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unsubscribe(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsubscribe(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsubscribe(arg0);
            return result;
        }
    }
    async updateEvent(arg0: bigint, arg1: TechEvent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, to_candid_TechEvent_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, to_candid_TechEvent_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_EventCategory_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventCategory): EventCategory {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_EventStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventStatus): EventStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_TechEvent_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TechEvent): TechEvent {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _EventStatus;
    registrationLimit: bigint;
    isPublished: boolean;
    bannerBlobId: [] | [string];
    currentRegistrations: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    isFree: boolean;
    specialInstructions: [] | [string];
    onlineLink: [] | [string];
    endDateTime: [] | [bigint];
    category: _EventCategory;
    price: number;
    dateTime: bigint;
    location: string;
}): {
    id: bigint;
    status: EventStatus;
    registrationLimit: bigint;
    isPublished: boolean;
    bannerBlobId?: string;
    currentRegistrations: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    isFree: boolean;
    specialInstructions?: string;
    onlineLink?: string;
    endDateTime?: bigint;
    category: EventCategory;
    price: number;
    dateTime: bigint;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_EventStatus_n22(_uploadFile, _downloadFile, value.status),
        registrationLimit: value.registrationLimit,
        isPublished: value.isPublished,
        bannerBlobId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.bannerBlobId)),
        currentRegistrations: value.currentRegistrations,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        isFree: value.isFree,
        specialInstructions: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.specialInstructions)),
        onlineLink: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.onlineLink)),
        endDateTime: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.endDateTime)),
        category: from_candid_EventCategory_n26(_uploadFile, _downloadFile, value.category),
        price: value.price,
        dateTime: value.dateTime,
        location: value.location
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    live: null;
} | {
    completed: null;
}): EventStatus {
    return "upcoming" in value ? EventStatus.upcoming : "live" in value ? EventStatus.live : "completed" in value ? EventStatus.completed : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    seminar: null;
} | {
    workshop: null;
} | {
    hackathon: null;
} | {
    podcast: null;
} | {
    webinar: null;
} | {
    techCarnival: null;
} | {
    summit: null;
} | {
    aiConference: null;
}): EventCategory {
    return "seminar" in value ? EventCategory.seminar : "workshop" in value ? EventCategory.workshop : "hackathon" in value ? EventCategory.hackathon : "podcast" in value ? EventCategory.podcast : "webinar" in value ? EventCategory.webinar : "techCarnival" in value ? EventCategory.techCarnival : "summit" in value ? EventCategory.summit : "aiConference" in value ? EventCategory.aiConference : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n30(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TechEvent>): Array<TechEvent> {
    return value.map((x)=>from_candid_TechEvent_n20(_uploadFile, _downloadFile, x));
}
function to_candid_EventCategory_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventCategory): _EventCategory {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_EventRegistration_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventRegistration): _EventRegistration {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_EventStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventStatus): _EventStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_TechEvent_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TechEvent): _TechEvent {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: EventStatus;
    registrationLimit: bigint;
    isPublished: boolean;
    bannerBlobId?: string;
    currentRegistrations: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    isFree: boolean;
    specialInstructions?: string;
    onlineLink?: string;
    endDateTime?: bigint;
    category: EventCategory;
    price: number;
    dateTime: bigint;
    location: string;
}): {
    id: bigint;
    status: _EventStatus;
    registrationLimit: bigint;
    isPublished: boolean;
    bannerBlobId: [] | [string];
    currentRegistrations: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    isFree: boolean;
    specialInstructions: [] | [string];
    onlineLink: [] | [string];
    endDateTime: [] | [bigint];
    category: _EventCategory;
    price: number;
    dateTime: bigint;
    location: string;
} {
    return {
        id: value.id,
        status: to_candid_EventStatus_n12(_uploadFile, _downloadFile, value.status),
        registrationLimit: value.registrationLimit,
        isPublished: value.isPublished,
        bannerBlobId: value.bannerBlobId ? candid_some(value.bannerBlobId) : candid_none(),
        currentRegistrations: value.currentRegistrations,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        isFree: value.isFree,
        specialInstructions: value.specialInstructions ? candid_some(value.specialInstructions) : candid_none(),
        onlineLink: value.onlineLink ? candid_some(value.onlineLink) : candid_none(),
        endDateTime: value.endDateTime ? candid_some(value.endDateTime) : candid_none(),
        category: to_candid_EventCategory_n14(_uploadFile, _downloadFile, value.category),
        price: value.price,
        dateTime: value.dateTime,
        location: value.location
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    eventId: bigint;
    name: string;
    createdAt: bigint;
    isPaid: boolean;
    email: string;
    stripePaymentId?: string;
    contactNumber: string;
    organization?: string;
}): {
    id: bigint;
    eventId: bigint;
    name: string;
    createdAt: bigint;
    isPaid: boolean;
    email: string;
    stripePaymentId: [] | [string];
    contactNumber: string;
    organization: [] | [string];
} {
    return {
        id: value.id,
        eventId: value.eventId,
        name: value.name,
        createdAt: value.createdAt,
        isPaid: value.isPaid,
        email: value.email,
        stripePaymentId: value.stripePaymentId ? candid_some(value.stripePaymentId) : candid_none(),
        contactNumber: value.contactNumber,
        organization: value.organization ? candid_some(value.organization) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventStatus): {
    upcoming: null;
} | {
    live: null;
} | {
    completed: null;
} {
    return value == EventStatus.upcoming ? {
        upcoming: null
    } : value == EventStatus.live ? {
        live: null
    } : value == EventStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventCategory): {
    seminar: null;
} | {
    workshop: null;
} | {
    hackathon: null;
} | {
    podcast: null;
} | {
    webinar: null;
} | {
    techCarnival: null;
} | {
    summit: null;
} | {
    aiConference: null;
} {
    return value == EventCategory.seminar ? {
        seminar: null
    } : value == EventCategory.workshop ? {
        workshop: null
    } : value == EventCategory.hackathon ? {
        hackathon: null
    } : value == EventCategory.podcast ? {
        podcast: null
    } : value == EventCategory.webinar ? {
        webinar: null
    } : value == EventCategory.techCarnival ? {
        techCarnival: null
    } : value == EventCategory.summit ? {
        summit: null
    } : value == EventCategory.aiConference ? {
        aiConference: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
